const BaseLauncher = require('./base');

/**
 * Parse an Amazon Games JSON export file.
 * Expected format: [{ productId: "uuid", title: "Game Name" }, ...]
 * Generated by tools/amazon-export.ps1
 */
function parseGamesJson(buffer) {
  let data;
  try {
    data = JSON.parse(buffer.toString('utf8'));
  } catch (err) {
    throw new Error('Failed to parse amazon-games.json: ' + err.message);
  }

  if (!Array.isArray(data)) {
    throw new Error('Expected a JSON array of games');
  }

  const games = data
    .filter(entry => entry.title && entry.title.trim().length > 0)
    .map(entry => ({
      launcher_game_id: entry.productId || entry.title,
      title: entry.title.trim(),
    }));

  games.sort((a, b) => a.title.localeCompare(b.title));
  return games;
}

class AmazonLauncher extends BaseLauncher {
  async fetchOwnedGames() {
    throw new Error('Amazon Games uses file import only — no API sync available.');
  }
}

module.exports = AmazonLauncher;
module.exports.parseGamesJson = parseGamesJson;
